/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 * @param `object`
 * @param metadata
 * @param uri
 */

data class ExtractionItemContainer(
    @Json(name = "object")
    val `object`: MediaObjectDescriptor? = null,
    @Json(name = "metadata")
    val metadata: kotlin.collections.List<MediaObjectMetadataDescriptor>? = null,
    @Json(name = "uri")
    val uri: kotlin.String? = null
)

