/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param queryId
 * @param featureMap
 * @param elementID
 */

data class FeaturesAllCategoriesQueryResult(
    @Json(name = "queryId")
    val queryId: kotlin.String? = null,
    @Json(name = "featureMap")
    val featureMap: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.Any>>? = null,
    @Json(name = "elementID")
    val elementID: kotlin.String? = null
)

