/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param segmentId
 * @param objectId
 * @param start
 * @param end
 * @param startabs
 * @param endabs
 * @param sequenceNumber
 * @param count
 */

data class MediaSegmentDescriptor(
    @Json(name = "segmentId")
    val segmentId: kotlin.String? = null,
    @Json(name = "objectId")
    val objectId: kotlin.String? = null,
    @Json(name = "start")
    val start: kotlin.Int? = null,
    @Json(name = "end")
    val end: kotlin.Int? = null,
    @Json(name = "startabs")
    val startabs: kotlin.Float? = null,
    @Json(name = "endabs")
    val endabs: kotlin.Float? = null,
    @Json(name = "sequenceNumber")
    val sequenceNumber: kotlin.Int? = null,
    @Json(name = "count")
    val count: kotlin.Int? = null
)

