/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param objectId
 * @param domain
 * @param key
 * @param value
 * @param exists
 */

data class MediaObjectMetadataDescriptor(
    @Json(name = "objectId")
    val objectId: kotlin.String? = null,
    @Json(name = "domain")
    val domain: kotlin.String? = null,
    @Json(name = "key")
    val key: kotlin.String? = null,
    @Json(name = "value")
    val value: kotlin.String? = null,
    @Json(name = "exists")
    val exists: kotlin.Boolean? = null
)

