/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param objectId
 * @param name
 * @param path
 * @param mediatype
 * @param exists
 * @param contentURL
 */

data class MediaObjectDescriptor(
    @Json(name = "objectId")
    val objectId: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "path")
    val path: kotlin.String? = null,
    @Json(name = "mediatype")
    val mediatype: MediaObjectDescriptor.Mediatype? = null,
    @Json(name = "exists")
    val exists: kotlin.Boolean? = null,
    @Json(name = "contentURL")
    val contentURL: kotlin.String? = null
) {

    /**
     *
     * Values: vIDEO,iMAGE,aUDIO,mODEL3D,iMAGESEQUENCE,uNKNOWN
     */
    enum class Mediatype(val value: kotlin.String) {
        @Json(name = "VIDEO")
        vIDEO("VIDEO"),

        @Json(name = "IMAGE")
        iMAGE("IMAGE"),

        @Json(name = "AUDIO")
        aUDIO("AUDIO"),

        @Json(name = "MODEL3D")
        mODEL3D("MODEL3D"),

        @Json(name = "IMAGE_SEQUENCE")
        iMAGESEQUENCE("IMAGE_SEQUENCE"),

        @Json(name = "UNKNOWN")
        uNKNOWN("UNKNOWN");
    }
}

