/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param type
 * @param data
 * @param categories
 */

data class QueryTerm(
    @Json(name = "type")
    val type: QueryTerm.Type? = null,
    @Json(name = "data")
    val data: kotlin.String? = null,
    @Json(name = "categories")
    val categories: kotlin.collections.List<kotlin.String>? = null
) {

    /**
     *
     * Values: iMAGE,aUDIO,mOTION,mODEL3D,lOCATION,tIME,tEXT,tAG,sEMANTIC,iD,bOOLEAN
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "IMAGE")
        iMAGE("IMAGE"),

        @Json(name = "AUDIO")
        aUDIO("AUDIO"),

        @Json(name = "MOTION")
        mOTION("MOTION"),

        @Json(name = "MODEL3D")
        mODEL3D("MODEL3D"),

        @Json(name = "LOCATION")
        lOCATION("LOCATION"),

        @Json(name = "TIME")
        tIME("TIME"),

        @Json(name = "TEXT")
        tEXT("TEXT"),

        @Json(name = "TAG")
        tAG("TAG"),

        @Json(name = "SEMANTIC")
        sEMANTIC("SEMANTIC"),

        @Json(name = "ID")
        iD("ID"),

        @Json(name = "BOOLEAN")
        bOOLEAN("BOOLEAN");
    }
}

