/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param id
 * @param validUntil
 * @param type
 * @param sessionId
 */

data class SessionState(
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "validUntil")
    val validUntil: kotlin.Long? = null,
    @Json(name = "type")
    val type: SessionState.Type? = null,
    @Json(name = "sessionId")
    val sessionId: kotlin.String? = null
) {

    /**
     *
     * Values: uNAUTHENTICATED,uSER,aDMIN
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "UNAUTHENTICATED")
        uNAUTHENTICATED("UNAUTHENTICATED"),

        @Json(name = "USER")
        uSER("USER"),

        @Json(name = "ADMIN")
        aDMIN("ADMIN");
    }
}

