/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 * @param description
 * @param name
 * @param priority
 * @param id
 */

data class Tag(
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "priority")
    val priority: Tag.Priority? = null,
    @Json(name = "id")
    val id: kotlin.String? = null
) {

    /**
     *
     * Values: rEQUEST,rEQUIRE,eXCLUDE
     */
    enum class Priority(val value: kotlin.String) {
        @Json(name = "REQUEST")
        rEQUEST("REQUEST"),

        @Json(name = "REQUIRE")
        rEQUIRE("REQUIRE"),

        @Json(name = "EXCLUDE")
        eXCLUDE("EXCLUDE");
    }
}

